# This file has been generated by dapp2nix 1.1.1, do not edit.

{ solidityPackage, solc, dapp2 }:

let
  inherit (builtins) map listToAttrs attrNames attrValues;
  mapAttrs = if (builtins ? mapAttrs)
    then builtins.mapAttrs
    else f: attrs:
      listToAttrs (map
        (name: { inherit name; value = f name attrs."${name}"; })
        (attrNames attrs));

  defaults = {
    inherit solc;
    test-hevm = dapp2.test-hevm;
    doCheck = true;
  };

  package = spec: let
    spec' = defaults // (removeAttrs spec [ "repo'" "src'" ]);
    deps = map (spec:
      package (spec // { inherit (spec') solc test-hevm doCheck; })
    ) (attrValues spec'.deps);
  in solidityPackage (spec' // { inherit deps; });

  packageSpecs = mapAttrs (_: package);

  specs = rec {
    ds-auth_434bf46 = rec {
      name = "ds-auth";
      deps = {
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-auth-434bf46-source";
        url = "https://github.com/dapphub/ds-auth";
        rev = "434bf463b255ecc2157b9c671139f6c617795ebf";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-chief_73e6889 = rec {
      name = "ds-chief";
      deps = {
        ds-roles = ds-roles_dbd4c1a;
        ds-test = ds-test_eb7148d;
        ds-thing = ds-thing_98c26fb;
        ds-token = ds-token_8943920;
      };
      repo' = {
        name = "ds-chief-73e6889-source";
        url = "https://github.com/dapphub/ds-chief";
        rev = "73e6889a1335b386d0b642d1439a29084d01df4d";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-exec_2acecab = rec {
      name = "ds-exec";
      deps = {
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-exec-2acecab-source";
        url = "https://github.com/dapphub/ds-exec";
        rev = "2acecab8404bb0215ce595ff606c8c663eedd89f";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-guard_12461a5 = rec {
      name = "ds-guard";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-guard-12461a5-source";
        url = "https://github.com/dapphub/ds-guard";
        rev = "12461a5282ee7316525d490da83a351209eb0b20";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-math_bd110d4 = rec {
      name = "ds-math";
      deps = {
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-math-bd110d4-source";
        url = "https://github.com/dapphub/ds-math";
        rev = "bd110d4bd7572637a5947aca0647e933b1332cd8";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-note_c673c9d = rec {
      name = "ds-note";
      deps = {
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-note-c673c9d-source";
        url = "https://github.com/dapphub/ds-note";
        rev = "c673c9d1a1464e973db4489221e22dc5b9b02319";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-pause_53700f6 = rec {
      name = "ds-pause";
      deps = {
        ds-chief = ds-chief_73e6889;
        ds-proxy = ds-proxy_4299be4;
        ds-spell = ds-spell_1324209;
        ds-test = ds-test_eb7148d;
        ds-token = ds-token_8943920;
      };
      repo' = {
        name = "ds-pause-53700f6-source";
        url = "https://github.com/dapphub/ds-pause";
        rev = "53700f6fb648911ab18ac080e97c5dfd2aa03f2e";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-proxy_4299be4 = rec {
      name = "ds-proxy";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-note = ds-note_c673c9d;
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-proxy-4299be4-source";
        url = "https://github.com/dapphub/ds-proxy";
        rev = "4299be40d5a76c02e690db055281d476a460a38b";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-roles_dbd4c1a = rec {
      name = "ds-roles";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-roles-dbd4c1a-source";
        url = "https://github.com/dapphub/ds-roles";
        rev = "dbd4c1a4f5aa2d64598fff69a12f773e2b4f4fa6";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-spell_1324209 = rec {
      name = "ds-spell";
      deps = {
        ds-exec = ds-exec_2acecab;
        ds-note = ds-note_c673c9d;
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-spell-1324209-source";
        url = "https://github.com/dapphub/ds-spell";
        rev = "1324209fff044e232c1279f9a292e6a488e58793";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-stop_d7fe123 = rec {
      name = "ds-stop";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-note = ds-note_c673c9d;
        ds-test = ds-test_a4e4005;
      };
      repo' = {
        name = "ds-stop-d7fe123-source";
        url = "https://github.com/dapphub/ds-stop";
        rev = "d7fe123558df655caa60e3d6c5f4bf8430d394ae";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-test_eb7148d = rec {
      name = "ds-test";
      deps = {};
      repo' = {
        name = "ds-test-eb7148d-source";
        url = "https://github.com/dapphub/ds-test";
        rev = "eb7148d43c1ca6f9890361e2e2378364af2430ba";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-thing_98c26fb = rec {
      name = "ds-thing";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-math = ds-math_bd110d4;
        ds-note = ds-note_c673c9d;
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "ds-thing-98c26fb-source";
        url = "https://github.com/dapphub/ds-thing";
        rev = "98c26fb5e6b09cd91eeec237bc18b9a0d7cce5dd";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-token_8943920 = rec {
      name = "ds-token";
      deps = {
        ds-math = ds-math_bd110d4;
        ds-stop = ds-stop_d7fe123;
        ds-test = ds-test_eb7148d;
        erc20 = erc20_f322aac;
      };
      repo' = {
        name = "ds-token-8943920-source";
        url = "https://github.com/dapphub/ds-token";
        rev = "8943920eedbf35853c45167403dc4e5620be16aa";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-value_0bc3c89 = rec {
      name = "ds-value";
      deps = {
        ds-test = ds-test_eb7148d;
        ds-thing = ds-thing_98c26fb;
      };
      repo' = {
        name = "ds-value-0bc3c89-source";
        url = "https://github.com/dapphub/ds-value";
        rev = "0bc3c89b3f503c5134649456102e442cf8c9a0a8";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    ds-weth_b5819d1 = rec {
      name = "ds-weth";
      deps = {
        ds-test = ds-test_eb7148d;
        erc20 = erc20_f322aac;
      };
      repo' = {
        name = "ds-weth-b5819d1-source";
        url = "https://github.com/reflexer-labs/ds-weth";
        rev = "b5819d1c088e1b750900b8539d6f7bfd6c0b28c7";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    geb_f13158d = rec {
      name = "geb";
      deps = {
        ds-test = ds-test_eb7148d;
      };
      repo' = {
        name = "geb-f13158d-source";
        url = "https://github.com/reflexer-labs/geb";
        rev = "f13158d4db4e0b7c3ef8cd576160fc249d8fafd9";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    erc20_f322aac = rec {
      name = "erc20";
      deps = {
      };
      repo' = {
        name = "erc20-f322aac-source";
        url = "https://github.com/dapphub/erc20";
        rev = "f322aaca414db343337814097d2af43214bee96c";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    esm_40e3b5a = rec {
      name = "esm";
      deps = {
        ds-test = ds-test_eb7148d;
        ds-token = ds-token_8943920;
      };
      repo' = {
        name = "esm-40e3b5a-source";
        url = "https://github.com/reflexer-labs/esm";
        rev = "40e3b5ae1ae02641599bdf9bed8e3ec02743dfd8";
        ref = "HEAD";
      };
      src' = fetchGit repo';
      src = "${src'}/src";
    };
    geb-deploy = rec {
      name = "geb-deploy";
      deps = {
        ds-auth = ds-auth_434bf46;
        ds-guard = ds-guard_12461a5;
        ds-pause = ds-pause_53700f6;
        ds-roles = ds-roles_dbd4c1a;
        ds-test = ds-test_eb7148d;
        ds-token = ds-token_8943920;
        ds-weth = ds-weth_b5819d1;
        geb = geb_f13158d;
        esm = esm_40e3b5a;
      };
      src' = ../.;
      src = ../src;
    };
    this = geb-deploy;
  };
in {
  inherit package packageSpecs specs;
  this = package specs.this;
  deps = packageSpecs specs.this.deps;
  version = "1.1.1";
}
